# S3 bucket for storing data generated by the Web App
resource "aws_s3_bucket" "webapp_data" {
  bucket = "cg-webapp-data-${random_string.lb_id.result}" 

  tags = var.resource_tags
}

# A resource to enable bucket versioning for data protection
resource "aws_s3_bucket_versioning" "webapp_data_versioning" {
  bucket = aws_s3_bucket.webapp_data.id

  versioning_configuration {
    status = "Enabled"
  }
}

# This policy allows EC2 instances to access the S3 bucket using IAM instance profile
data "aws_iam_policy_document" "s3_bucket_policy" {
  statement {
    actions = [
      "s3:GetObject",
      "s3:PutObject",
      "s3:ListBucket"
    ]

    resources = [
      aws_s3_bucket.webapp_data.arn,
      "${aws_s3_bucket.webapp_data.arn}/*"
    ]

    principals {
      type        = "AWS"
      identifiers = ["*"] # Replace with EC2 role ARN if tighter control is required
    }

    # Allow access only through the VPN CIDR block
    condition {
      test     = "IpAddress"
      variable = "aws:SourceIp"
      values   = ["10.100.0.0/16"]
    }
  }
}

resource "aws_s3_bucket_policy" "webapp_data_policy" {
  bucket = aws_s3_bucket.webapp_data.id
  policy = data.aws_iam_policy_document.s3_bucket_policy.json
}

# A VPC Gateway endpoint to enable secure access to the S3 bucket from private subnets
resource "aws_vpc_endpoint" "s3_gateway" {
  vpc_id       = module.vpc.vpc_id
  service_name = "com.amazonaws.${var.aws_region}.s3"
  vpc_endpoint_type = "Gateway"
  route_table_ids   = module.vpc.private_route_table_ids

  tags = var.resource_tags
}